name: test_WF1
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print data
        run: echo "Hellow world !"
      - name: print data2
        run: echo "Welcome......."
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: print some more data
        run: |
          echo "This is second job"
          echo "second job line2"
          echo "second job line3"
